### PR TITLE
Add a basic test and CI

### PR DESCRIPTION
**Pull request by mj-will**
Add a very basic test and CI

These should be updated in another PR since I'm unsure if the CI will run for this PR.

### CODE REVIEW

**Comment by mj-will** [comment]
@WuShichao do you have any option to run the CI I've added in this MR? (See https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks for details)

**Comment by mj-will** [comment]
After talking with @spxiwh, it seems this PR will likely need to be made from a branch on the main repo rather than my fork. I don't have permission to push to the repo, so I'll need someone else to that or to add me for the permissions.

**Comment by spxiwh** [comment]
Invite sent, let me know if it doesn't give you what you need

**Comment by mj-will** [comment]
Thanks @spxiwh, that seems to have changed my permissions for the main pycbc repo, but not for this one (I can't push or add e.g. labels for PRs). I'm guessing this one isn't included in those related to the `Maintainers` group.

**Comment by spxiwh** [comment]
Try again now, I've played with group settings.

**Comment by mj-will** [comment]
Thanks, that seems to have worked

**Comment by WuShichao** [comment]
Thanks, I have approved this https://github.com/gwastro/BBHX-waveform-model/pull/8 but I didn't see the CI test.

**Pull request closed without merging**
